z_min: 0
z_max: 1
N_z: 6 #amount of redshift points to sample from
z_sources: 1 #redshift at which sources are located (its a dirac delta distribution)
l_min: 10
l_max: 1e6
N_l: 80
Delta_vir: 200
M_max: 1e16
M_min: 1e5
N_M: 70
k_max: 1e4
k_min: 1e-3
N_k: 50
d_vir: 1
m_min: 1
